version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: "Top 10 Companies"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'  # Added MySQL port
    networks:
      - common-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - '8080:80'
    networks:
      - common-network

volumes:
  db_data:

networks:
  common-network:
